# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MYP@SSWORD"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./Database/Data:/var/opt/mssql/data
  api:
    image: backendherhalingsneakers
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    
