// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_herhaling_sneakers.Data;

namespace backend_herhaling_sneakers.Migrations
{
    [DbContext(typeof(SneakerContext))]
    [Migration("20210317104432_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OccasionSneaker", b =>
                {
                    b.Property<Guid>("OccasionsOccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SneakersSneakerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsOccasionId", "SneakersSneakerId");

                    b.HasIndex("SneakersSneakerId");

                    b.ToTable("OccasionSneaker");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = new Guid("8a0ec09e-c95a-4742-a110-1479f4fb17ae"),
                            Name = "ASICS"
                        },
                        new
                        {
                            BrandId = new Guid("ced64b94-0a55-4261-9768-8d2642c4b31f"),
                            Name = "CONVERSE"
                        },
                        new
                        {
                            BrandId = new Guid("e05fe524-6151-47e9-b657-6bdfd17e9878"),
                            Name = "VANS"
                        },
                        new
                        {
                            BrandId = new Guid("c29537bd-68e7-43b3-9d59-665df7994846"),
                            Name = "NIKE"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Occasion", b =>
                {
                    b.Property<Guid>("OccasionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionId");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionId = new Guid("61c3f4af-fd76-483b-a25f-d5b8f57dcf92"),
                            Name = "Sports"
                        },
                        new
                        {
                            OccasionId = new Guid("1c35de5b-66d7-4c8e-a465-a7cbb0ae64f7"),
                            Name = "Casual"
                        },
                        new
                        {
                            OccasionId = new Guid("9cd2a7dc-e207-4e3a-b2cd-1a54d88bf259"),
                            Name = "Skate"
                        },
                        new
                        {
                            OccasionId = new Guid("66f0cff2-d913-4827-bf60-ed3e6d10b758"),
                            Name = "Diner"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Sneaker", b =>
                {
                    b.Property<Guid>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("SneakerId");

                    b.ToTable("Sneakers");
                });

            modelBuilder.Entity("OccasionSneaker", b =>
                {
                    b.HasOne("backend_herhaling_sneakers.Models.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsOccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_herhaling_sneakers.Models.Sneaker", null)
                        .WithMany()
                        .HasForeignKey("SneakersSneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
