// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_herhaling_sneakers.Data;

namespace backend_herhaling_sneakers.Migrations
{
    [DbContext(typeof(SneakerContext))]
    [Migration("20210318130142_feedback dieter")]
    partial class feedbackdieter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = new Guid("6be65aa1-b05e-4bbd-9cf9-d7965aae3b6b"),
                            Name = "ASICS"
                        },
                        new
                        {
                            BrandId = new Guid("124fd704-c95f-491e-8830-afb2ea306efd"),
                            Name = "CONVERSE"
                        },
                        new
                        {
                            BrandId = new Guid("48881100-82b9-4093-8937-a420e8d20451"),
                            Name = "VANS"
                        },
                        new
                        {
                            BrandId = new Guid("c92fabe2-ef96-4cfa-9ce4-824b85c4a5bf"),
                            Name = "NIKE"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SneakerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Occasion", b =>
                {
                    b.Property<Guid>("OccasionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionId");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionId = new Guid("593ff6f2-d6d5-4a68-8a56-0724eca02e92"),
                            Name = "Sports"
                        },
                        new
                        {
                            OccasionId = new Guid("4c3d4523-5cbb-45b2-ac13-a66efe04a177"),
                            Name = "Casual"
                        },
                        new
                        {
                            OccasionId = new Guid("9fd2a7a0-ffbe-49d4-b79a-2539e37a7a7a"),
                            Name = "Skate"
                        },
                        new
                        {
                            OccasionId = new Guid("b4b949c9-2e78-45ef-bf3b-4a6e7f2c6afa"),
                            Name = "Diner"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Sneaker", b =>
                {
                    b.Property<Guid>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("SneakerId");

                    b.ToTable("Sneakers");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.SneakerOccasion", b =>
                {
                    b.Property<Guid>("SneakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SneakerId", "OccasionId");

                    b.HasIndex("OccasionId");

                    b.ToTable("SneakerOccasions");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.SneakerOccasion", b =>
                {
                    b.HasOne("backend_herhaling_sneakers.Models.Occasion", null)
                        .WithMany("SneakerOccasions")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_herhaling_sneakers.Models.Sneaker", null)
                        .WithMany("SneakerOccasions")
                        .HasForeignKey("SneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Occasion", b =>
                {
                    b.Navigation("SneakerOccasions");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Sneaker", b =>
                {
                    b.Navigation("SneakerOccasions");
                });
#pragma warning restore 612, 618
        }
    }
}
