// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_herhaling_sneakers.Data;

namespace backend_herhaling_sneakers.Migrations
{
    [DbContext(typeof(SneakerContext))]
    [Migration("20210317104923_added sneaker image rel")]
    partial class addedsneakerimagerel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OccasionSneaker", b =>
                {
                    b.Property<Guid>("OccasionsOccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SneakersSneakerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsOccasionId", "SneakersSneakerId");

                    b.HasIndex("SneakersSneakerId");

                    b.ToTable("OccasionSneaker");
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = new Guid("207e4d2a-eafe-4316-a202-d7d3df1140c0"),
                            Name = "ASICS"
                        },
                        new
                        {
                            BrandId = new Guid("4af8a6a4-81fa-4427-a81e-0e00322f8c96"),
                            Name = "CONVERSE"
                        },
                        new
                        {
                            BrandId = new Guid("80a90a7f-7913-489c-9b8b-79d9a9bfb979"),
                            Name = "VANS"
                        },
                        new
                        {
                            BrandId = new Guid("384d303b-fe21-470a-a11f-24a33e3e2ca1"),
                            Name = "NIKE"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Occasion", b =>
                {
                    b.Property<Guid>("OccasionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionId");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionId = new Guid("356cda4b-58ba-4630-b739-8881d52ca0db"),
                            Name = "Sports"
                        },
                        new
                        {
                            OccasionId = new Guid("959dc696-56cf-4b92-a3a9-c1924b635909"),
                            Name = "Casual"
                        },
                        new
                        {
                            OccasionId = new Guid("e0f930c0-e041-41ad-bffb-109acfd83f31"),
                            Name = "Skate"
                        },
                        new
                        {
                            OccasionId = new Guid("6a635ea3-97b6-4892-8153-6b8d63ac28d3"),
                            Name = "Diner"
                        });
                });

            modelBuilder.Entity("backend_herhaling_sneakers.Models.Sneaker", b =>
                {
                    b.Property<Guid>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("SneakerId");

                    b.ToTable("Sneakers");
                });

            modelBuilder.Entity("OccasionSneaker", b =>
                {
                    b.HasOne("backend_herhaling_sneakers.Models.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsOccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_herhaling_sneakers.Models.Sneaker", null)
                        .WithMany()
                        .HasForeignKey("SneakersSneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
